// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-o_xCeBmsuDPBHum244cnqJGhuujPzY',
    appId: '1:478852115396:web:b61c5799c33778fbc09291',
    messagingSenderId: '478852115396',
    projectId: 'imgroot',
    authDomain: 'imgroot.firebaseapp.com',
    databaseURL: 'https://imgroot-default-rtdb.firebaseio.com',
    storageBucket: 'imgroot.appspot.com',
    measurementId: 'G-8F1XJZDYHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuB9NgQbQij_blUhFjxea58wtUgRU3Vvc',
    appId: '1:478852115396:android:15c6ac06c14cefb3c09291',
    messagingSenderId: '478852115396',
    projectId: 'imgroot',
    databaseURL: 'https://imgroot-default-rtdb.firebaseio.com',
    storageBucket: 'imgroot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdi4vtI7EtkdxFZf3kRK5VJUmtfiz7Yb8',
    appId: '1:478852115396:ios:e7be57061e57ef29c09291',
    messagingSenderId: '478852115396',
    projectId: 'imgroot',
    databaseURL: 'https://imgroot-default-rtdb.firebaseio.com',
    storageBucket: 'imgroot.appspot.com',
    androidClientId: '478852115396-1durf00nodnea55j3o6qp6gagh1corga.apps.googleusercontent.com',
    iosClientId: '478852115396-71squ9sqicbqsebc8v6jd1k8n18j9n10.apps.googleusercontent.com',
    iosBundleId: 'com.example.seuLourival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdi4vtI7EtkdxFZf3kRK5VJUmtfiz7Yb8',
    appId: '1:478852115396:ios:e7be57061e57ef29c09291',
    messagingSenderId: '478852115396',
    projectId: 'imgroot',
    databaseURL: 'https://imgroot-default-rtdb.firebaseio.com',
    storageBucket: 'imgroot.appspot.com',
    androidClientId: '478852115396-1durf00nodnea55j3o6qp6gagh1corga.apps.googleusercontent.com',
    iosClientId: '478852115396-71squ9sqicbqsebc8v6jd1k8n18j9n10.apps.googleusercontent.com',
    iosBundleId: 'com.example.seuLourival',
  );
}
